import QRCode from 'qrcode';
import jsQR from 'jsqr';
import { PNG } from 'pngjs';
import { getReportShareUrl, extractReportDataFromUrl, getAppBaseUrl, DEFAULT_PUBLIC_APP_URL } from './src/utils/qrPayload.ts';

console.log('============================================================');
console.log('🔍 TESTING PRODUCTION REPORT QR CODE URL GENERATION & FIX');
console.log('============================================================\n');

const sampleReport = {
  name: 'गणेश शिंदे',
  mobile: '7972532010',
  village: 'धारूर रोड, केज',
  age: '29',
  gender: 'Male',
  height: '174',
  date: '01/10/2026',
  weight: '76.4',
  idealWeight: '68.0',
  extraWeight: '8.4 kg',
  lessWeight: '-',
  bodyFat: '21.5',
  visceralFat: '10',
  restingMetabolism: '1620',
  bmi: '25.2',
  bodyAge: '33',
  subWhole: '17.8',
  subArms: '18.4',
  subTrunk: '16.0',
  subLegs: '19.8',
  skelWhole: '35.2',
  skelArms: '43.0',
  skelTrunk: '29.0',
  skelLegs: '48.0',
  measArms: '14.0',
  measWaist: '34.5',
  measThigh: '21.5',
  reportId: 'BAR-MUPCA5FR-2X77',
  createdAt: '2026-10-01T10:00:00.000Z',
};

// TEST CASE 1: Native Android App (simulating WebView origin 'https://localhost')
console.log('--- TEST CASE 1: Native Android App on Phone A ---');
// In WebView, window.location.origin is 'https://localhost'
globalThis.window = {
  location: {
    origin: 'https://localhost',
    pathname: '/',
    search: '',
    hash: '',
  },
  localStorage: {
    getItem: () => null,
  },
};

const androidReportUrl = getReportShareUrl(sampleReport);
console.log('Generated QR URL on Android:', androidReportUrl);

if (androidReportUrl.includes('localhost') || androidReportUrl.includes('127.0.0.1')) {
  console.error('❌ FAILED: Android QR code contained localhost!');
  process.exit(1);
}
if (!androidReportUrl.startsWith(DEFAULT_PUBLIC_APP_URL)) {
  console.error(`❌ FAILED: Expected URL to start with ${DEFAULT_PUBLIC_APP_URL}`);
  process.exit(1);
}
console.log(`✅ PASSED: Android app produces public URL: ${DEFAULT_PUBLIC_APP_URL}/report/BAR-MUPCA5FR-2X77?d=...`);
console.log('✅ PASSED: No "https://localhost" is emitted!');

// TEST CASE 2: Deployed Public Website (e.g. Vercel, Netlify, Custom Domain)
console.log('\n--- TEST CASE 2: Deployed Web Host at Runtime ---');
const deployedOrigin = 'https://baliraja-fitness-app.vercel.app';
globalThis.window = {
  location: {
    origin: deployedOrigin,
    pathname: '/report',
    search: '',
    hash: '',
  },
  localStorage: {
    getItem: () => null,
  },
};

const deployedReportUrl = getReportShareUrl(sampleReport);
console.log('Generated QR URL on Deployed Web:', deployedReportUrl);

if (!deployedReportUrl.startsWith(`${deployedOrigin}/report/${sampleReport.reportId}?d=`)) {
  console.error(`❌ FAILED: Deployed web did not use actual origin: ${deployedOrigin}`);
  process.exit(1);
}
console.log(`✅ PASSED: Deployed web dynamically uses: ${deployedOrigin}/report/BAR-MUPCA5FR-2X77?d=...`);

// TEST CASE 3: Phone B Scans the QR Code generated by Phone A
console.log('\n--- TEST CASE 3: Phone B Scans QR & Reconstructs Report ---');
const qrBuffer = await QRCode.toBuffer(deployedReportUrl, {
  margin: 2,
  width: 400,
  errorCorrectionLevel: 'M',
  color: { dark: '#000000', light: '#ffffff' },
});

const png = PNG.sync.read(qrBuffer);
const scannedCode = jsQR(new Uint8ClampedArray(png.data), png.width, png.height);

if (!scannedCode || scannedCode.data !== deployedReportUrl) {
  console.error('❌ FAILED: Optical scanner failed to decode QR code!');
  process.exit(1);
}
console.log('Scanned QR URL:', scannedCode.data);

// Simulate Phone B loading this URL in its browser
const { report: reconstructedReport, reportId } = extractReportDataFromUrl(scannedCode.data);

if (!reconstructedReport) {
  console.error('❌ FAILED: Could not extract report data from scanned URL!');
  process.exit(1);
}

if (
  reconstructedReport.name !== sampleReport.name ||
  reconstructedReport.mobile !== sampleReport.mobile ||
  reconstructedReport.weight !== sampleReport.weight ||
  reconstructedReport.bodyFat !== sampleReport.bodyFat ||
  reconstructedReport.visceralFat !== sampleReport.visceralFat ||
  reconstructedReport.restingMetabolism !== sampleReport.restingMetabolism ||
  reconstructedReport.bmi !== sampleReport.bmi ||
  reconstructedReport.reportId !== sampleReport.reportId
) {
  console.error('❌ FAILED: Reconstructed report fields do not match original!');
  process.exit(1);
}

console.log(`✅ PASSED: Phone B successfully reconstructed complete report for "${reconstructedReport.name}"!`);
console.log(`   - Weight: ${reconstructedReport.weight} kg`);
console.log(`   - Body Fat: ${reconstructedReport.bodyFat} %`);
console.log(`   - Visceral Fat: ${reconstructedReport.visceralFat}`);
console.log(`   - Resting Metabolism: ${reconstructedReport.restingMetabolism} kcal`);
console.log(`   - BMI: ${reconstructedReport.bmi}`);
console.log(`   - Report ID: ${reconstructedReport.reportId}`);

// TEST CASE 4: Explicit customBaseUrl override
console.log('\n--- TEST CASE 4: Custom Base URL Override ---');
const customUrl = getReportShareUrl(sampleReport, 'https://mycustomfitness.org');
if (!customUrl.startsWith('https://mycustomfitness.org/report/BAR-MUPCA5FR-2X77?d=')) {
  console.error('❌ FAILED: customBaseUrl override did not work!');
  process.exit(1);
}
console.log('✅ PASSED: customBaseUrl override successfully applied:', customUrl.substring(0, 70) + '...');

console.log('\n============================================================');
console.log('🎉 ALL PRODUCTION REPORT QR URL FIX CHECKS PASSED 100%!');
console.log('============================================================\n');
